// <auto-generated />
using System;
using Aeroblock.DataAccess.Rail;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Aeroblock.DataAccess.Rail.Migrations
{
    [DbContext(typeof(RailDbContext))]
    partial class RailDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Aeroblock.DataAccess.Rail.Models.OrderRzdEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Col")
                        .HasColumnType("int");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Costumer")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DateOrder")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Fact")
                        .HasColumnType("int");

                    b.Property<string>("Material")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Old")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("Order")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("SumWeight")
                        .HasColumnType("int");

                    b.Property<string>("Weight")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("OrderRzds");
                });

            modelBuilder.Entity("Aeroblock.DataAccess.Rail.Models.VagonVihodEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Costumer")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("costumer");

                    b.Property<DateTime?>("Date")
                        .HasColumnType("DATETIME")
                        .HasColumnName("date");

                    b.Property<DateTime?>("Finish")
                        .HasColumnType("DATETIME")
                        .HasColumnName("data_finish");

                    b.Property<bool?>("IsPrihod")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false)
                        .HasColumnName("prihod");

                    b.Property<bool?>("IsStart")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false)
                        .HasColumnName("status_start");

                    b.Property<bool?>("IsStop")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false)
                        .HasColumnName("status_stop");

                    b.Property<string>("Material")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("material");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("number");

                    b.Property<string>("NumberSilos")
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("number_silos");

                    b.Property<int?>("OrderId")
                        .HasColumnType("int")
                        .HasColumnName("id_order");

                    b.Property<string>("Partial")
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("partia");

                    b.Property<DateTime?>("Prihod")
                        .HasColumnType("DATETIME")
                        .HasColumnName("data_prihod");

                    b.Property<string>("Sender")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("sender");

                    b.Property<DateTime?>("Start")
                        .HasColumnType("DATETIME")
                        .HasColumnName("data_start");

                    b.Property<string>("Time")
                        .HasMaxLength(5)
                        .HasColumnType("varchar(5)")
                        .HasColumnName("time");

                    b.Property<DateTime?>("VagonFinish")
                        .HasColumnType("DATETIME")
                        .HasColumnName("vag_finish");

                    b.Property<int>("Weight")
                        .HasColumnType("int")
                        .HasColumnName("weight");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.ToTable("vagon_vihods");
                });
#pragma warning restore 612, 618
        }
    }
}
