// <auto-generated />
using System;
using Aeroblock.DataAccess.Rail;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Aeroblock.DataAccess.Rail.Migrations
{
    [DbContext(typeof(RailDbContext))]
    partial class RailDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("latin1_bin")
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Aeroblock.DataAccess.Rail.Models.CountryEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(11)
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.ToTable("countrys");
                });

            modelBuilder.Entity("Aeroblock.DataAccess.Rail.Models.DeliveryTermEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(11)
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasMaxLength(245)
                        .HasColumnType("varchar(245)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.ToTable("delivery_terms");
                });

            modelBuilder.Entity("Aeroblock.DataAccess.Rail.Models.ManufacturerEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(11)
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Adress")
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("adress");

                    b.Property<string>("ContactFace")
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("contact_face");

                    b.Property<string>("Email")
                        .HasMaxLength(145)
                        .HasColumnType("varchar(145)")
                        .HasColumnName("e_mail");

                    b.Property<string>("Face")
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("face");

                    b.Property<string>("Name")
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("name");

                    b.Property<string>("Phone")
                        .HasMaxLength(145)
                        .HasColumnType("varchar(145)")
                        .HasColumnName("tel");

                    b.Property<string>("Site")
                        .HasMaxLength(145)
                        .HasColumnType("varchar(145)")
                        .HasColumnName("site");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.ToTable("manufacturers");
                });

            modelBuilder.Entity("Aeroblock.DataAccess.Rail.Models.NameMaterialEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(11)
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Group")
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("group");

                    b.Property<string>("Name")
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.ToTable("name_materials");
                });

            modelBuilder.Entity("Aeroblock.DataAccess.Rail.Models.NdsEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(11)
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.ToTable("ndss");
                });

            modelBuilder.Entity("Aeroblock.DataAccess.Rail.Models.OrderRzdEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(11)
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("Col")
                        .HasMaxLength(11)
                        .HasColumnType("int")
                        .HasColumnName("col");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("comments");

                    b.Property<string>("Costumer")
                        .IsRequired()
                        .HasMaxLength(125)
                        .HasColumnType("varchar(125)")
                        .HasColumnName("costumer");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("DATE")
                        .HasColumnName("date");

                    b.Property<DateOnly>("DateOrder")
                        .HasColumnType("DATE")
                        .HasColumnName("date_order");

                    b.Property<int?>("Fact")
                        .HasMaxLength(11)
                        .HasColumnType("int")
                        .HasColumnName("fact");

                    b.Property<string>("Material")
                        .IsRequired()
                        .HasMaxLength(35)
                        .HasColumnType("varchar(35)")
                        .HasColumnName("material");

                    b.Property<string>("Old")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("varchar(5)")
                        .HasColumnName("old");

                    b.Property<bool>("Order")
                        .HasMaxLength(1)
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("change_order");

                    b.Property<int?>("SumWeight")
                        .HasMaxLength(11)
                        .HasColumnType("int")
                        .HasColumnName("sum_weight");

                    b.Property<float?>("Weight")
                        .HasColumnType("FLOAT")
                        .HasColumnName("weight_1");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.ToTable("order_rzds");
                });

            modelBuilder.Entity("Aeroblock.DataAccess.Rail.Models.PaymentTermEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(11)
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("Delay")
                        .HasMaxLength(11)
                        .HasColumnType("int")
                        .HasColumnName("delay");

                    b.Property<string>("Name")
                        .HasMaxLength(145)
                        .HasColumnType("varchar(145)")
                        .HasColumnName("name");

                    b.Property<int?>("PaymentFinal")
                        .HasMaxLength(11)
                        .HasColumnType("int")
                        .HasColumnName("payment_final");

                    b.Property<int?>("Prepayment")
                        .HasMaxLength(11)
                        .HasColumnType("int")
                        .HasColumnName("prepayment");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.ToTable("payment_terms");
                });

            modelBuilder.Entity("Aeroblock.DataAccess.Rail.Models.SiloBalanceEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(11)
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Manufactur")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("manufactur");

                    b.Property<float?>("MaxWeight")
                        .HasColumnType("float")
                        .HasColumnName("max_weight");

                    b.Property<string>("SiloMaterialName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("silo_material_name");

                    b.Property<string>("SiloNameSendler")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("silo_name_sendler");

                    b.Property<int?>("SiloNum")
                        .HasMaxLength(11)
                        .HasColumnType("int")
                        .HasColumnName("silo_num");

                    b.Property<float?>("Weight")
                        .HasColumnType("float(10, 0)")
                        .HasColumnName("weight");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.ToTable("silo_balances");
                });

            modelBuilder.Entity("Aeroblock.DataAccess.Rail.Models.SkladEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(11)
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("name");

                    b.Property<string>("NameMaterial")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("name_material");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.ToTable("sklads");
                });

            modelBuilder.Entity("Aeroblock.DataAccess.Rail.Models.VagonVihodEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Costumer")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("costumer")
                        .UseCollation("utf8_general_ci");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("Costumer"), "utf8");

                    b.Property<DateTime?>("Date")
                        .HasColumnType("DATETIME")
                        .HasColumnName("date");

                    b.Property<DateTime?>("Finish")
                        .HasColumnType("DATETIME")
                        .HasColumnName("data_finish");

                    b.Property<bool?>("IsPrihod")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false)
                        .HasColumnName("prihod");

                    b.Property<bool?>("IsStart")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false)
                        .HasColumnName("status_start");

                    b.Property<bool?>("IsStop")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false)
                        .HasColumnName("status_stop");

                    b.Property<string>("Material")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("material")
                        .UseCollation("utf8_general_ci");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("Material"), "utf8");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("number")
                        .UseCollation("utf8_general_ci");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("Number"), "utf8");

                    b.Property<string>("NumberSilos")
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("number_silos")
                        .UseCollation("utf8_general_ci");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("NumberSilos"), "utf8");

                    b.Property<int?>("OrderId")
                        .HasColumnType("int")
                        .HasColumnName("id_order");

                    b.Property<string>("Partial")
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("partia")
                        .UseCollation("utf8_general_ci");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("Partial"), "utf8");

                    b.Property<DateTime?>("Prihod")
                        .HasColumnType("DATETIME")
                        .HasColumnName("data_prihod");

                    b.Property<string>("Sender")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("sender")
                        .UseCollation("utf8_general_ci");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("Sender"), "utf8");

                    b.Property<DateTime?>("Start")
                        .HasColumnType("DATETIME")
                        .HasColumnName("data_start");

                    b.Property<string>("Time")
                        .HasMaxLength(5)
                        .HasColumnType("varchar(5)")
                        .HasColumnName("time")
                        .UseCollation("latin1_swedish_ci");

                    b.Property<DateTime?>("VagonFinish")
                        .HasColumnType("DATETIME")
                        .HasColumnName("vag_finish");

                    b.Property<int>("Weight")
                        .HasColumnType("int")
                        .HasColumnName("weight");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique()
                        .HasDatabaseName("id_UNIQUE");

                    b.ToTable("vagon_vihod");
                });

            modelBuilder.Entity("CostumerEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(11)
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Adress")
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("adress");

                    b.Property<string>("Email")
                        .HasMaxLength(145)
                        .HasColumnType("varchar(145)")
                        .HasColumnName("e_mail");

                    b.Property<string>("Face")
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("face");

                    b.Property<string>("FaceContract")
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("contact_face");

                    b.Property<string>("Name")
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("name");

                    b.Property<string>("Site")
                        .HasMaxLength(145)
                        .HasColumnType("varchar(145)")
                        .HasColumnName("site");

                    b.Property<string>("Tel")
                        .HasMaxLength(145)
                        .HasColumnType("varchar(145)")
                        .HasColumnName("tel");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.ToTable("costumers");
                });
#pragma warning restore 612, 618
        }
    }
}
